### ISSUE TITLE
Remove global `expo-cli` installation

### ISSUE THREAD

**Issue by karlhorky** [upleveled/system-setup#57]
Right now, we install `expo-cli` globally, but I think this is deprecated now, so probably we should remove this step

Verify that it has been deprecated / is no longer recommended and then remove it from all guides

**Comment by ProchaLu** [comment]
In Expo SDK 46, the Local Expo CLI got introduced, described by @EvanBacon in this [blogpost](https://blog.expo.dev/the-new-expo-cli-f4250d8e3421). Users no longer need to run `pnpm add -g expo-cli` as the CLI is shipped with the expo package. 

To install `expo-cli` we can now run `pnpm add expo`, because Expo CLI is included in the [expo package](https://docs.expo.dev/more/expo-cli/#installation).
